[project]
name = "{{ cookiecutter.project_name.lower().replace(' ', '_') }}"
version = "0.1.0"
description = "{{ cookiecutter.description }}"
authors = ["{{ cookiecutter.author_name }}"]
license = "MIT"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    python = ">=3.10"
    numpy = "^1.26.1"
    pandas = "^2.1.1"
    matplotlib = "^3.8.0"
    scikit-learn = "^1.3.1"
    loguru = "^0.7.2"
    tqdm = "^4.66.1"
    # einops = "^0.7.0"
    # simple-parsing = "^0.1.4"
    # torch = {version = "^2.1.0+cu124", source = "pytorch"}
    # lightning = "^2.1.0"
    # pytorch-optimizer = "^2.12.0"
    # torchinfo = "^1.8.0"
    # accelerate = "^0.24.1"
    # transformers = "4.34.0"
    # accelerate = "^0.24.1"
    # peft = "^0.5.0"
    # loguru = "^0.7.2"
    # einops = "^0.3.1"
]

[dependency-groups]
dev = [
    "ipykernel>=6.29.5",
    "ipywidgets>=8.1.5",
    "pytest>=8.0.2",
    "ruff>=0.8.3",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
