name: $(PROJECT_NAME)
channels:
  - pytorch
  - conda-forge
  - main
  - defaults
dependencies:
  - python=3.7
  - pip
  - ipykernel
  # external requirements
  - awscli
  - python-dotenv
  - pip:
    # local package
    - -e ..

